import { createContext, useContext } from "react";
import { Listing } from "../model/Listing";

let list: Listing = {
  listingKey: 0,
  enumerateKey: 0,
  reg: "",
  cwt: "",
  amp: "",
  tam: "",
  area: "",
  mun: "",
  tao: "",
  vil: "",
  aea: "",
  sT_A: "",
  sT_B: "",
  sT_C: "",
  fN_A: "",
  fN_B: "",
  fN_C: "",
  enU_A: "",
  enU_B: "",
  enU_C: "",
  acA_A: "",
  acA_B: "",
  acA_C: "",
  suB_A: "",
  suB_B: "",
  suB_C: "",
  r01: "",
  f1CODE: "",
  r02_A: "",
  r02_B: "",
  r02_C: "",
  r02_D: "",
  r03_A: "",
  r03_AT: "",
  r03_B: "",
  r03_C: "",
  lat: "",
  long: "",
  r04: "",
  pid: "",
  bd: "",
  r05: "",
  r06: "",
  r07: "",
  r08: "",
  r09: "",
  r10: "",
  r11: "",
  r12: "",
  r13_A: "",
  r13_AT: "",
  r13_B: "",
  r13_C: "",
  r14: "",
  r15: "",
  r16_A: "",
  r16_B: "",
  r16_C: "",
  r17: "",
  r18: "",
  r19: "",
  r20: "",
  r21: "",
  r22: "",
  r23: "",
  r24: "",
  r25: "",
  r26: "",
  r27: "",
  r28_A: "",
  r28_AT: "",
  r28_B: "",
  r28_C: "",
  r28_D: "",
  r28_E: "",
  r28_F: "",
  r28_J: "",
  r28_I: "",
  r29: "",
  r30: "",
  r31: "",
  r32: "",
  r33: "",
  r34: "",
  r35: "",
  r36: "",
  r37: "",
  r38_A: "",
  r38_B: "",
  r38_C: "",
  r38_G: "",
  r38_H: "",
  r39: "",
  r40: "",
  reG_N: "",
  cwT_N: "",
  amP_N: "",
  taM_N: "",
  muN_N: "",
  taO_N: "",
  viL_N: "",
  createBy: 0,
  aH_CODE: "",
  subRecordR08: 0,
  subRecordR12: 0,
  status:"",
  areA_CODE:"",
  iS_FARMER: "",
  statusE:"",
  p1_A:"",
  sdatE_A: "",
  sdatE_B: "",
  sdatE_C: "",
  cdatE_A: "",
  cdatE_B: "",
  cdatE_C: "",
  isTracking: "",
};

export type GlobalContent = {
  listing: Listing | null;
  setListing: (c: Listing) => void;
  noFarmer: boolean;
  setNoFarmer: (n: boolean) => void;
  page: number;
  setPage: (p: number) => void;
};

export const ListingContext = createContext<GlobalContent>({
  listing: list, // set a default value
  setListing: () => {},
  noFarmer: false,
  setNoFarmer: () => {},
  page: 0,
  setPage: () => {},
});
export const useGlobalListingContext = () => useContext(ListingContext);
