import { createContext, useContext } from "react";
import { Listing2 } from "../model/Listing2";

let defaultValue: Listing2 = {
  TempKey: 0,
  AREA_CODE: "",
  REG: "",
  REGN: "",
  CWT: "",
  CWTN: "",
  AMP: "",
  AMPN: "",
  TAM: "",
  TAMN: "",
  TYPE: "",
  MUN: "",
  MUNN: "",
  VIL: "",
  VILN: "",
  VILT: "",
  ST_A: "",
  ST_B: "",
  ST_C: "",
  ST_Time: "",
  FN_A: "",
  FN_B: "",
  FN_C: "",
  FN_Time: "",
  ENU_A: "",
  ENU_B: "",
  ENU_C: "",
  ACA_A: "",
  ACA_B: "",
  ACA_C: "",
  SUB_A: "",
  SUB_B: "",
  SUB_C: "",
  ENO: "",
  F1CODE: "",
  Eadd_A: "",
  Eadd_B: "",
  Eadd_C: "",
  Eadd_D: "",
  Ename_A: "",
  Ename_AT: "",
  Ename_B: "",
  Ename_C: "",
  Esex: "",
  EPID: "",
  EBD: "",
  ESI: "",
  status1: "",
  R01: "",
  R02: "",
  R03_A: "",
  R03_B: "",
  R03_C: "",
  lat: "",
  long: "",
  R07: "",
  R08: "",
  R08_sub: "",
  R09: "",
  R10: "",
  R11: "",
  R12: "",
  R12_sub: "",
  R13_A: "",
  R13_AT: "",
  R13_B: "",
  R13_C: "",
  R14: "",
  R15: "",
  R16_A: "",
  R16_B: "",
  R16_C: "",
  R17: "",
  R18: "",
  R19: "",
  R20: "",
  R21: "",
  R22: "",
  R23: "",
  R24: "",
  R25: "",
  R26: "",
  R27: "",
  Status2: "",
  R28: "",
  R29_A: "",
  R29_AT: "",
  R29_B: "",
  R29_C: "",
  R29_D: "",
  R29_E: "",
  R29_F: "",
  R29_G: "",
  R29_H: "",
  R29_I: "",
  R30: "",
  R31: "",
  R32: "",
  R33: "",
  R34: "",
  R35: "",
  R36: "",
  R37_A: "",
  R37_B: "",
  R37_C: "",
  R37_D: "",
  R37_E: "",
  R37_F: "",
  R37_G: "",
  ENU: "",
  AH_CODE: "", //Enumerate
  AH_CODE1: "", //TempListing
  FromE: "",
  Status: "",
  Active: "",
  IsTracking: "",
  TrackingStatus: "",
  IsMakeUp: "",
  SDATE_A: "",
  SDATE_B: "",
  SDATE_C: "",
  CDATE_A: "",
  CDATE_B: "",
  CDATE_C: "",
  P1_A: "",
  FROM_AREA_CODE: "",
  FROM_ADD: "",
};

export type GlobalContent = {
  listing: Listing2;
  setListing: (c: Listing2) => void;
  noFarmer: boolean;
  setNoFarmer: (n: boolean) => void;
  page: number;
  setPage: (p: number) => void;
};

export const Listing2Context = createContext<GlobalContent>({
  listing: defaultValue, // set a default value
  setListing: () => {},
  noFarmer: false,
  setNoFarmer: () => {},
  page: 0,
  setPage: () => {},
});
export const useGlobalListingContext = () => useContext(Listing2Context);
