export interface Listing {
    listingKey:number;
    enumerateKey:number;
    reg: string
    cwt: string;
    amp: string;
    tam: string;
    area: string;
    mun: string;
    tao: string;
    vil: string;
    aea: string;
    sT_A: string;
    sT_B: string;
    sT_C: string;
    fN_A: string;
    fN_B: string;
    fN_C: string;
    enU_A: string;
    enU_B: string;
    enU_C: string;
    acA_A: string;
    acA_B: string;
    acA_C: string;
    suB_A: string;
    suB_B: string;
    suB_C: string;
    r01: string;
    f1CODE: string;
    r02_A: string;
    r02_B: string;
    r02_C: string;
    r02_D: string;
    r03_A: string;
    r03_AT: string;
    r03_B: string;
    r03_C: string;
    lat: string;
    long: string;
    r04: string;
    pid: string;
    bd: string;
    r05: string;
    r06: string;
    r07: string;
    r08: string;
    r09: string;
    r10: string;
    r11: string;
    r12: string;
    r13_A: string;
    r13_AT: string;
    r13_B: string;
    r13_C: string;
    r14: string;
    r15: string;
    r16_A: string;
    r16_B: string;
    r16_C: string;
    r17: string;
    r18: string;
    r19: string;
    r20: string;
    r21: string;
    r22: string;
    r23: string;
    r24: string;
    r25: string;
    r26: string;
    r27: string;
    r28_A: string;
    r28_AT: string;
    r28_B: string;
    r28_C: string;
    r28_D: string;
    r28_E: string;
    r28_F: string;
    r28_J: string;
    r28_I: string;
    r29: string;
    r30: string;
    r31: string;
    r32: string;
    r33: string;
    r34: string;
    r35: string;
    r36: string;
    r37: string;
    r38_A: string;
    r38_B: string;
    r38_C: string;
    r38_G: string;
    r38_H: string;
    r39: string;
    r40: string;
    reG_N: string;
    cwT_N: string;
    amP_N: string;
    taM_N: string;
    muN_N: string;
    taO_N: string;
    viL_N: string;
    createBy: number;
    aH_CODE:string;
    subRecordR08:number;
    subRecordR12:number;
    status:string;
    areA_CODE:string;
    iS_FARMER:string;
    statusE:string;
    p1_A:string;
    sdatE_A: string;
    sdatE_B: string;
    sdatE_C: string;
    cdatE_A: string;
    cdatE_B: string;
    cdatE_C: string;
    isTracking:string;
}
